# Generated by Django 5.2.3 on 2025-09-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.player')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.quiz')),
            ],
        ),
    ]
