# Generated by Django 5.2.3 on 2025-09-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerquiz',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
