# Generated by Django 5.2.3 on 2025-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playerquiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='xp',
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
