# Generated by Django 5.2.3 on 2025-06-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz'),
    ]

    operations = [
    ]