# Generated by Django 5.2.3 on 2025-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_player_xp_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
