# Generated by Django 5.2.3 on 2025-06-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=150)),
                ('alternative_a', models.CharField(max_length=120)),
                ('alternative_b', models.CharField(max_length=120)),
                ('alternative_c', models.CharField(max_length=120)),
                ('alternative_d', models.CharField(max_length=120)),
                ('response', models.CharField(max_length=1)),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quiz')),
            ],
        ),
    ]