# Generated by Django 5.2.3 on 2025-07-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quiz_image_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'),
        ),
        migrations.CreateModel(
            name='PlayerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveSmallIntegerField()),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.player')),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.quiz')),
            ],
            options={
                'verbose_name_plural': 'Player Quizzes',
                'unique_together': {('id_player', 'id_quiz')},
            },
        ),
    ]
