# Generated by Django 5.2.3 on 2025-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.CharField(max_length=200),
        ),
    ]
