# Generated by Django 5.2.3 on 2025-07-14 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_playerquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerquestion',
            unique_together={('id_question', 'id_quiz', 'id_player', 'hit')},
        ),
    ]
