# Generated by Django 5.2.3 on 2025-09-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_playerquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_classroom',
        ),
    ]
