# Generated by Django 5.2.3 on 2025-10-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_playerquestion_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerquiz',
            options={},
        ),
        migrations.RenameField(
            model_name='playerquestion',
            old_name='id_player',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerquestion',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='playerquestion',
            old_name='id_quiz',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='playerquiz',
            old_name='id_player',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerquiz',
            old_name='id_quiz',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id_quiz',
            new_name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='playerquiz',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='id_classroom',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='xp',
        ),
        migrations.AddField(
            model_name='player',
            name='photo_path',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerquiz',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='playerquestion',
            unique_together={('question', 'quiz', 'player', 'hit')},
        ),
    ]
