# Generated by Django 5.2.3 on 2025-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_player_user_player_photo_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
