# Generated by Django 5.2.3 on 2025-09-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.AddField(
            model_name='player',
            name='path_foto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
