# Generated by Django 5.2.3 on 2025-09-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_player_photo_player_path_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='path_foto',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
