# Generated by Django 5.2.3 on 2025-09-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_player_path_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='path_foto',
            new_name='photo_path',
        ),
    ]
