# Generated by Django 5.2.3 on 2025-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_path_foto_player_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
